// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2013-2026 Christophe Clienti
#include <veriparse/AST/node_type.hpp>
#include <vector>

namespace Veriparse
{
namespace AST
{

const char *NodeTypeToString(NodeType node_type)
{
    switch(node_type) {
    case NodeType::Node:
        return "Node";
    case NodeType::Source:
        return "Source";
    case NodeType::Description:
        return "Description";
    case NodeType::Pragmalist:
        return "Pragmalist";
    case NodeType::Pragma:
        return "Pragma";
    case NodeType::Module:
        return "Module";
    case NodeType::Port:
        return "Port";
    case NodeType::Package:
        return "Package";
    case NodeType::Import:
        return "Import";
    case NodeType::Identifier:
        return "Identifier";
    case NodeType::Constant:
        return "Constant";
    case NodeType::StringConst:
        return "StringConst";
    case NodeType::IntConst:
        return "IntConst";
    case NodeType::IntConstN:
        return "IntConstN";
    case NodeType::FloatConst:
        return "FloatConst";
    case NodeType::DataType:
        return "DataType";
    case NodeType::LogicType:
        return "LogicType";
    case NodeType::RegType:
        return "RegType";
    case NodeType::BitType:
        return "BitType";
    case NodeType::ByteType:
        return "ByteType";
    case NodeType::ShortintType:
        return "ShortintType";
    case NodeType::IntType:
        return "IntType";
    case NodeType::LongintType:
        return "LongintType";
    case NodeType::IntegerType:
        return "IntegerType";
    case NodeType::TimeType:
        return "TimeType";
    case NodeType::RealType:
        return "RealType";
    case NodeType::ShortrealType:
        return "ShortrealType";
    case NodeType::RealtimeType:
        return "RealtimeType";
    case NodeType::StringType:
        return "StringType";
    case NodeType::ChandleType:
        return "ChandleType";
    case NodeType::EventType:
        return "EventType";
    case NodeType::ImplicitType:
        return "ImplicitType";
    case NodeType::VoidType:
        return "VoidType";
    case NodeType::NamedType:
        return "NamedType";
    case NodeType::ScopeName:
        return "ScopeName";
    case NodeType::StructType:
        return "StructType";
    case NodeType::UnionType:
        return "UnionType";
    case NodeType::EnumType:
        return "EnumType";
    case NodeType::EnumItem:
        return "EnumItem";
    case NodeType::TypeOpExpr:
        return "TypeOpExpr";
    case NodeType::TypeOpType:
        return "TypeOpType";
    case NodeType::Dimension:
        return "Dimension";
    case NodeType::RangeDim:
        return "RangeDim";
    case NodeType::SizeDim:
        return "SizeDim";
    case NodeType::UnsizedDim:
        return "UnsizedDim";
    case NodeType::QueueDim:
        return "QueueDim";
    case NodeType::AssocDim:
        return "AssocDim";
    case NodeType::Declaration:
        return "Declaration";
    case NodeType::Var:
        return "Var";
    case NodeType::Net:
        return "Net";
    case NodeType::WireNet:
        return "WireNet";
    case NodeType::TriNet:
        return "TriNet";
    case NodeType::Tri0Net:
        return "Tri0Net";
    case NodeType::Tri1Net:
        return "Tri1Net";
    case NodeType::TriandNet:
        return "TriandNet";
    case NodeType::TriorNet:
        return "TriorNet";
    case NodeType::TriregNet:
        return "TriregNet";
    case NodeType::WandNet:
        return "WandNet";
    case NodeType::WorNet:
        return "WorNet";
    case NodeType::UwireNet:
        return "UwireNet";
    case NodeType::Supply0Net:
        return "Supply0Net";
    case NodeType::Supply1Net:
        return "Supply1Net";
    case NodeType::InterconnectNet:
        return "InterconnectNet";
    case NodeType::UserNet:
        return "UserNet";
    case NodeType::ImplicitNet:
        return "ImplicitNet";
    case NodeType::NetTypeDecl:
        return "NetTypeDecl";
    case NodeType::Strength:
        return "Strength";
    case NodeType::DriveStrength:
        return "DriveStrength";
    case NodeType::ChargeStrength:
        return "ChargeStrength";
    case NodeType::Param:
        return "Param";
    case NodeType::TypeParam:
        return "TypeParam";
    case NodeType::Typedef:
        return "Typedef";
    case NodeType::Member:
        return "Member";
    case NodeType::Arg:
        return "Arg";
    case NodeType::Genvar:
        return "Genvar";
    case NodeType::Concat:
        return "Concat";
    case NodeType::Lconcat:
        return "Lconcat";
    case NodeType::Repeat:
        return "Repeat";
    case NodeType::AssignmentPattern:
        return "AssignmentPattern";
    case NodeType::PatternItem:
        return "PatternItem";
    case NodeType::Cast:
        return "Cast";
    case NodeType::TypeCast:
        return "TypeCast";
    case NodeType::SizeCast:
        return "SizeCast";
    case NodeType::SigningCast:
        return "SigningCast";
    case NodeType::ConstCast:
        return "ConstCast";
    case NodeType::Indirect:
        return "Indirect";
    case NodeType::Partselect:
        return "Partselect";
    case NodeType::PartselectIndexed:
        return "PartselectIndexed";
    case NodeType::PartselectPlusIndexed:
        return "PartselectPlusIndexed";
    case NodeType::PartselectMinusIndexed:
        return "PartselectMinusIndexed";
    case NodeType::Pointer:
        return "Pointer";
    case NodeType::Lvalue:
        return "Lvalue";
    case NodeType::Rvalue:
        return "Rvalue";
    case NodeType::UnaryOperator:
        return "UnaryOperator";
    case NodeType::Uplus:
        return "Uplus";
    case NodeType::Uminus:
        return "Uminus";
    case NodeType::Ulnot:
        return "Ulnot";
    case NodeType::Unot:
        return "Unot";
    case NodeType::Uand:
        return "Uand";
    case NodeType::Unand:
        return "Unand";
    case NodeType::Uor:
        return "Uor";
    case NodeType::Unor:
        return "Unor";
    case NodeType::Uxor:
        return "Uxor";
    case NodeType::Uxnor:
        return "Uxnor";
    case NodeType::Operator:
        return "Operator";
    case NodeType::Power:
        return "Power";
    case NodeType::Times:
        return "Times";
    case NodeType::Divide:
        return "Divide";
    case NodeType::Mod:
        return "Mod";
    case NodeType::Plus:
        return "Plus";
    case NodeType::Minus:
        return "Minus";
    case NodeType::Sll:
        return "Sll";
    case NodeType::Srl:
        return "Srl";
    case NodeType::Sra:
        return "Sra";
    case NodeType::LessThan:
        return "LessThan";
    case NodeType::GreaterThan:
        return "GreaterThan";
    case NodeType::LessEq:
        return "LessEq";
    case NodeType::GreaterEq:
        return "GreaterEq";
    case NodeType::Eq:
        return "Eq";
    case NodeType::NotEq:
        return "NotEq";
    case NodeType::Eql:
        return "Eql";
    case NodeType::NotEql:
        return "NotEql";
    case NodeType::And:
        return "And";
    case NodeType::Xor:
        return "Xor";
    case NodeType::Xnor:
        return "Xnor";
    case NodeType::Or:
        return "Or";
    case NodeType::Land:
        return "Land";
    case NodeType::Lor:
        return "Lor";
    case NodeType::Cond:
        return "Cond";
    case NodeType::Always:
        return "Always";
    case NodeType::AlwaysFF:
        return "AlwaysFF";
    case NodeType::AlwaysComb:
        return "AlwaysComb";
    case NodeType::AlwaysLatch:
        return "AlwaysLatch";
    case NodeType::Senslist:
        return "Senslist";
    case NodeType::Sens:
        return "Sens";
    case NodeType::Defparamlist:
        return "Defparamlist";
    case NodeType::Defparam:
        return "Defparam";
    case NodeType::Assign:
        return "Assign";
    case NodeType::BlockingSubstitution:
        return "BlockingSubstitution";
    case NodeType::NonblockingSubstitution:
        return "NonblockingSubstitution";
    case NodeType::IfStatement:
        return "IfStatement";
    case NodeType::RepeatStatement:
        return "RepeatStatement";
    case NodeType::ForStatement:
        return "ForStatement";
    case NodeType::WhileStatement:
        return "WhileStatement";
    case NodeType::CaseStatement:
        return "CaseStatement";
    case NodeType::CasexStatement:
        return "CasexStatement";
    case NodeType::CasezStatement:
        return "CasezStatement";
    case NodeType::UniqueCaseStatement:
        return "UniqueCaseStatement";
    case NodeType::PriorityCaseStatement:
        return "PriorityCaseStatement";
    case NodeType::Case:
        return "Case";
    case NodeType::Block:
        return "Block";
    case NodeType::Initial:
        return "Initial";
    case NodeType::EventStatement:
        return "EventStatement";
    case NodeType::WaitStatement:
        return "WaitStatement";
    case NodeType::ForeverStatement:
        return "ForeverStatement";
    case NodeType::DelayStatement:
        return "DelayStatement";
    case NodeType::Instancelist:
        return "Instancelist";
    case NodeType::Instance:
        return "Instance";
    case NodeType::ParamArg:
        return "ParamArg";
    case NodeType::PortArg:
        return "PortArg";
    case NodeType::Function:
        return "Function";
    case NodeType::FunctionCall:
        return "FunctionCall";
    case NodeType::Task:
        return "Task";
    case NodeType::TaskCall:
        return "TaskCall";
    case NodeType::GenerateStatement:
        return "GenerateStatement";
    case NodeType::SystemCall:
        return "SystemCall";
    case NodeType::HierLabel:
        return "HierLabel";
    case NodeType::HierName:
        return "HierName";
    case NodeType::Disable:
        return "Disable";
    case NodeType::ParallelBlock:
        return "ParallelBlock";
    case NodeType::SingleStatement:
        return "SingleStatement";
    default:
        return "Unknown NodeType";
    }
}

std::ostream &operator<<(std::ostream &os, const NodeType node_type)
{
    os << NodeTypeToString(node_type);
    return os;
}

std::ostream &operator<<(std::ostream &os, const std::vector<NodeType> &node_categories)
{
    os << "[";
    for(const NodeType &cat : node_categories) {
        os << NodeTypeToString(cat);
        if(cat != node_categories.back()) {
            os << ", ";
        }
    }
    os << "]";
    return os;
}

} // namespace AST
} // namespace Veriparse