// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2013-2026 Christophe Clienti
#ifndef VERIPARSE_AST_NODE_TYPE_HPP
#define VERIPARSE_AST_NODE_TYPE_HPP

#include <iostream>

namespace Veriparse
{
namespace AST
{

enum class NodeType
{
    Source,
    Description,
    Pragmalist,
    Pragma,
    Module,
    Port,
    Width,
    Length,
    Identifier,
    Constant,
    StringConst,
    IntConst,
    IntConstN,
    FloatConst,
    IODir,
    Input,
    Output,
    Inout,
    VariableBase,
    Genvar,
    Variable,
    CustomTypeVar,
    Net,
    Integer,
    Real,
    Byte,
    Shortint,
    Int,
    Longint,
    Shortreal,
    Realtime,
    Bit,
    Tri,
    Wire,
    Supply0,
    Supply1,
    Logic,
    Reg,
    Ioport,
    Parameter,
    Localparam,
    Concat,
    Lconcat,
    Repeat,
    AssignmentPattern,
    PatternItem,
    Cast,
    Indirect,
    Partselect,
    PartselectIndexed,
    PartselectPlusIndexed,
    PartselectMinusIndexed,
    Pointer,
    Lvalue,
    Rvalue,
    UnaryOperator,
    Uplus,
    Uminus,
    Ulnot,
    Unot,
    Uand,
    Unand,
    Uor,
    Unor,
    Uxor,
    Uxnor,
    Operator,
    Power,
    Times,
    Divide,
    Mod,
    Plus,
    Minus,
    Sll,
    Srl,
    Sra,
    LessThan,
    GreaterThan,
    LessEq,
    GreaterEq,
    Eq,
    NotEq,
    Eql,
    NotEql,
    And,
    Xor,
    Xnor,
    Or,
    Land,
    Lor,
    Cond,
    Always,
    AlwaysFF,
    AlwaysComb,
    AlwaysLatch,
    Senslist,
    Sens,
    Defparamlist,
    Defparam,
    Assign,
    BlockingSubstitution,
    NonblockingSubstitution,
    IfStatement,
    RepeatStatement,
    ForStatement,
    WhileStatement,
    CaseStatement,
    CasexStatement,
    CasezStatement,
    UniqueCaseStatement,
    PriorityCaseStatement,
    Case,
    Block,
    Initial,
    EventStatement,
    WaitStatement,
    ForeverStatement,
    DelayStatement,
    Instancelist,
    Instance,
    ParamArg,
    PortArg,
    Function,
    FunctionCall,
    Task,
    TaskCall,
    GenerateStatement,
    SystemCall,
    IdentifierScopeLabel,
    IdentifierScope,
    Disable,
    ParallelBlock,
    SingleStatement,
    EnumItem,
    EnumDef,
    Typedef,
    StructMember,
    StructUnionDef,
    StructDef,
    Union,
    Package,
    Import,
    Node,
    None
};

const char *NodeTypeToString(NodeType node_type);

std::ostream &operator<<(std::ostream &os, const NodeType node_type);

} // namespace AST
} // namespace Veriparse

#endif