// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2013-2026 Christophe Clienti
#ifndef VERIPARSE_AST_NODE_TYPE_HPP
#define VERIPARSE_AST_NODE_TYPE_HPP

#include <iostream>

namespace Veriparse
{
namespace AST
{

enum class NodeType
{
    Source,
    Description,
    Pragmalist,
    Pragma,
    Module,
    Port,
    Package,
    Import,
    Identifier,
    Constant,
    StringConst,
    IntConst,
    IntConstN,
    FloatConst,
    DataType,
    LogicType,
    RegType,
    BitType,
    ByteType,
    ShortintType,
    IntType,
    LongintType,
    IntegerType,
    TimeType,
    RealType,
    ShortrealType,
    RealtimeType,
    StringType,
    ChandleType,
    EventType,
    ImplicitType,
    VoidType,
    NamedType,
    ScopeName,
    StructType,
    UnionType,
    EnumType,
    EnumItem,
    TypeOpExpr,
    TypeOpType,
    Dimension,
    RangeDim,
    SizeDim,
    UnsizedDim,
    QueueDim,
    AssocDim,
    Declaration,
    Var,
    Net,
    WireNet,
    TriNet,
    Tri0Net,
    Tri1Net,
    TriandNet,
    TriorNet,
    TriregNet,
    WandNet,
    WorNet,
    UwireNet,
    Supply0Net,
    Supply1Net,
    InterconnectNet,
    UserNet,
    ImplicitNet,
    NetTypeDecl,
    Strength,
    DriveStrength,
    ChargeStrength,
    Param,
    TypeParam,
    Typedef,
    Member,
    Arg,
    Genvar,
    Concat,
    Lconcat,
    Repeat,
    AssignmentPattern,
    PatternItem,
    Cast,
    TypeCast,
    SizeCast,
    SigningCast,
    ConstCast,
    Indirect,
    Partselect,
    PartselectIndexed,
    PartselectPlusIndexed,
    PartselectMinusIndexed,
    Pointer,
    Lvalue,
    Rvalue,
    UnaryOperator,
    Uplus,
    Uminus,
    Ulnot,
    Unot,
    Uand,
    Unand,
    Uor,
    Unor,
    Uxor,
    Uxnor,
    Operator,
    Power,
    Times,
    Divide,
    Mod,
    Plus,
    Minus,
    Sll,
    Srl,
    Sra,
    LessThan,
    GreaterThan,
    LessEq,
    GreaterEq,
    Eq,
    NotEq,
    Eql,
    NotEql,
    And,
    Xor,
    Xnor,
    Or,
    Land,
    Lor,
    Cond,
    Always,
    AlwaysFF,
    AlwaysComb,
    AlwaysLatch,
    Senslist,
    Sens,
    Defparamlist,
    Defparam,
    Assign,
    BlockingSubstitution,
    NonblockingSubstitution,
    IfStatement,
    RepeatStatement,
    ForStatement,
    WhileStatement,
    CaseStatement,
    CasexStatement,
    CasezStatement,
    UniqueCaseStatement,
    PriorityCaseStatement,
    Case,
    Block,
    Initial,
    EventStatement,
    WaitStatement,
    ForeverStatement,
    DelayStatement,
    Instancelist,
    Instance,
    ParamArg,
    PortArg,
    Function,
    FunctionCall,
    Task,
    TaskCall,
    GenerateStatement,
    SystemCall,
    HierLabel,
    HierName,
    Disable,
    ParallelBlock,
    SingleStatement,
    Node,
    None
};

const char *NodeTypeToString(NodeType node_type);

std::ostream &operator<<(std::ostream &os, const NodeType node_type);

} // namespace AST
} // namespace Veriparse

#endif