#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2013-2026 Christophe Clienti
"""ADR-0014 §10.2 consumer: a verilower state map into a wavedisp description.

The JSON is the canonical record of what the source does not state — the
encoding, the state names, the reset contract. Viewer knowledge lives in
wavedisp, so this script only bridges: per compiled process it emits a
Group holding the state register with its symbolic value table, the reset
signal, and the registers the reset branch writes.

Usage:  fsm_wavedisp.py <output.fsm.json> [<description.py>]
"""

import json
import sys


def generate(map_path, out_path):
    with open(map_path, encoding="utf-8") as handle:
        report = json.load(handle)

    lines = [
        '"""Wavedisp description generated by fsm_wavedisp.py from %s."""' % map_path,
        "",
        "from wavedisp.ast import Hierarchy, Group, Disp",
        "",
        "",
        "def generator():",
        "    hier = Hierarchy()",
    ]

    for process in report["processes"]:
        states = {state["value"]: state["name"] for state in process["states"]}
        lines += [
            "    grp = Group('FSM %s')" % process["module"],
            "    hier.add(grp)",
            "    # symbolic value table: %s" % states,
            "    grp.add(Disp('%s', radix='symbolic'))" % process["state_variable"],
            "    grp.add(Disp('%s'))" % process["reset"]["signal"],
        ]
        for register in process["reset"]["registers"]:
            if register != process["state_variable"]:
                lines.append("    grp.add(Disp('%s'))" % register)

    lines += ["    return hier", ""]

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    map_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else map_path + ".wavedisp.py"
    generate(map_path, out_path)
    print("wavedisp description written to %s" % out_path)


if __name__ == "__main__":
    main()
