package:
  name: veriparse
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ../..

build:
  number: 0
  ignore_run_exports:
    - gtest

requirements:
  host:
    - gmp=6.3.0
    - flex=2.6.4
    - gtest=1.17.0
    - boost=1.85.0
    - yaml-cpp=0.8.0

  run:
    - gmp=6.3.0
    - boost=1.85.0
    - yaml-cpp=0.8.0

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make
    - cmake
    - mold  # [not win]
    - flex=2.6.4
    - bison=3.8.2
    - boost=1.85.0
    - yaml-cpp=0.8.0
    - gmp=6.3.0
    - gtest=1.17.0

about:
  home: https://www.wavecruncher.net
  license: LGPL-3.0-only
  license_file: ../../LICENSE
  summary: Verilog Design Flattenner and Obfuscater.

test:
  commands:
    - veriparse -h
    - veriflat -h
    - veriobf -h
