package:
  name: veriparse
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ../..

build:
  number: 0
  ignore_run_exports:
    - boost
    - yaml-cpp
    - gmp
    - gtest
    - openssl

requirements:
  run:
    - gmp=6.2.0

  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - flex
    - bison
    - boost=1.72
    - yaml-cpp=0.6.3
    - gmp=6.2.0
    - gtest=1.10.0
    - openssl=1.1.1d

about:
  home: https://www.wavecruncher.net
  license: Christophe Clienti, All Rights Reserved.
  license_file: ../../licenses/LICENSE
  summary: Verilog Design Flattenner and Obfuscater.
