set(GOOGLETEST_GIT_PREFIX_DIR ${CMAKE_CURRENT_BINARY_DIR}/external/googletest)
set(GOOGLETEST_GIT_INSTALL_DIR ${GOOGLETEST_GIT_PREFIX_DIR}/install)

message(STATUS "External project google test installation in ${GOOGLETEST_GIT_INSTALL_DIR}")

set(GTEST_LIBRARY gtest)
get_filename_component(GTEST_LIBRARY_PATH
  ${GOOGLETEST_GIT_INSTALL_DIR}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}${GTEST_LIBRARY}${CMAKE_STATIC_LIBRARY_SUFFIX}
  REALPATH)

set(GTEST_MAIN_LIBRARY gtest_main)
get_filename_component(GTEST_MAIN_LIBRARY_PATH
  ${GOOGLETEST_GIT_INSTALL_DIR}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}${GTEST_MAIN_LIBRARY}${CMAKE_STATIC_LIBRARY_SUFFIX}
  REALPATH)

set(GMOCK_LIBRARY gmock)
get_filename_component(GMOCK_LIBRARY_PATH
  ${GOOGLETEST_GIT_INSTALL_DIR}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}${GMOCK_LIBRARY}${CMAKE_STATIC_LIBRARY_SUFFIX}
  REALPATH)

set(GMOCK_MAIN_LIBRARY gmock_main)
get_filename_component(GMOCK_MAIN_LIBRARY_PATH
  ${GOOGLEMOCK_GIT_INSTALL_DIR}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}${GMOCK_LIBRARY}${CMAKE_STATIC_LIBRARY_SUFFIX}
  REALPATH)

ExternalProject_Add(googletest-git
    BUILD_IN_SOURCE   1
    PREFIX             ${GOOGLETEST_GIT_PREFIX_DIR}
    GIT_REPOSITORY    "https://github.com/google/googletest.git"
    GIT_TAG           "ec44c6c"
    CMAKE_ARGS        "-DCMAKE_INSTALL_PREFIX=${GOOGLETEST_GIT_INSTALL_DIR}"
    UPDATE_COMMAND    ""
    BUILD_BYPRODUCTS  ${GTEST_LIBRARY_PATH} ${GTEST_MAIN_LIBRARY_PATH}
                      ${GMOCK_LIBRARY_PATH} ${GMOCK_MAIN_LIBRARY_PATH}
)

set_directory_properties(PROPERTY CLEAN_NO_CUSTOM ${GOOGLETEST_GIT_PREFIX_DIR})

# Include directory
set (GTEST_INCLUDE_DIRS ${GOOGLETEST_GIT_INSTALL_DIR}/include)

# Libs declaration
add_library(${GTEST_LIBRARY} STATIC IMPORTED)
set_property(TARGET ${GTEST_LIBRARY} PROPERTY IMPORTED_LOCATION ${GTEST_LIBRARY_PATH})
add_dependencies(${GTEST_LIBRARY} googletest-git)

add_library(${GTEST_MAIN_LIBRARY} STATIC IMPORTED)
set_property(TARGET ${GTEST_MAIN_LIBRARY} PROPERTY IMPORTED_LOCATION ${GTEST_MAIN_LIBRARY_PATH})
add_dependencies(${GTEST_MAIN_LIBRARY} googletest-git)

add_library(${GMOCK_LIBRARY} STATIC IMPORTED)
set_property(TARGET ${GMOCK_LIBRARY} PROPERTY IMPORTED_LOCATION ${GMOCK_LIBRARY_PATH})
add_dependencies(${GMOCK_LIBRARY} googletest-git)

add_library(${GMOCK_MAIN_LIBRARY} STATIC IMPORTED)
set_property(TARGET ${GMOCK_MAIN_LIBRARY} PROPERTY IMPORTED_LOCATION ${GMOCK_MAIN_LIBRARY_PATH})
add_dependencies(${GMOCK_MAIN_LIBRARY} googletest-git)

set(GTEST_BOTH_LIBRARIES gtest gtest_main)
set(GMOCK_BOTH_LIBRARIES gmock gmock_main)
