name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install mold linker
        run: sudo apt-get install -y mold iverilog

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          init-shell: bash

      - name: Generate conda environment file
        run: make dev-env-file

      - name: Create dev environment
        run: make dev-env

      - name: Configure
        run: make dev-cmake

      - name: Build
        run: make dev-build

      - name: Test (unittest)
        run: make dev-test

      - name: Test (verilator + integration)
        run: make dev-test-integration
